services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=1708266613@qq.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_network

  web:
    build:
      context: /home/azureuser/LeagueofLegends/LeagueofLegends
      dockerfile: Dockerfile
    container_name: leagueoflegends-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`leagueweb.chickenkiller.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    restart: always
    networks:
      - traefik_network
    environment:
      - NODE_ENV=production

networks:
  traefik_network:
