name: Build and Deploy Docker Compose

on:
  push:
    branches:
      - main  # 监听 main 分支的提交
  pull_request:  # 可选：监听 pull request
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 设置 Docker 环境
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. 登录 Docker Registry (Azure ACR)
    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login cloudproject2024.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

    # 4. 构建和推送 Docker 镜像到 Azure ACR
    - name: Build and Push Docker Image
      run: |
        docker build -t cloudproject2024.azurecr.io/leagueoflegends:latest ./LeagueofLegends
        docker push cloudproject2024.azurecr.io/leagueoflegends:latest

    # 5. 登录到 Azure VM 并部署 Docker Compose
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
        port: 22
        script: |
          # 转到目标目录并克隆/更新项目
          cd /home/azureuser
          if [ ! -d "LeagueOfLegends" ]; then
           git clone https://github.com/AP-G-1PRO-Webontwikkeling/project-webontwikkeling-MengranHao1998.git LeagueOfLegends
          else
           cd LeagueOfLegends
           git pull  # 更新已有项目
          fi

# 运行 Docker Compose
          cd /home/azureuser/LeagueOfLegends
          docker-compose down
          docker-compose up -d --build

